COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mssql+pyodbc://olezhka:Sqlroot365@cloud-course-db.database.windows.net:1433/cloud-course-db?driver=ODBC+Driver+18+for+SQL+Server'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mssql+pyodbc://olezhka:Sqlroot365@cloud-course-db.database.windows.net:1433/cloud-course-db?driver=ODBC+Driver+18+for+SQL+Server'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: root
